---
- name: Install PgBouncer
  package:
    name: pgbouncer
    state: present
  register: _pgbouncer_install

- name: Create pgbouncer directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: 0755
  with_items:
    - "{{ pgbouncer_log_dir }}"
    - "{{ pgbouncer_pid_dir }}"

- name: Create pgbouncer service file
  template:
    src: pgbouncer.service.j2
    dest: /lib/systemd/system/pgbouncer@.service
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: 0600
  notify:
    - Reload pgbouncer

- name: Create pgbouncer socket file
  template:
    src: pgbouncer.socket.j2
    dest: /lib/systemd/system/pgbouncer@.socket
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: 0600
  notify:
    - Reload pgbouncer

- name: Create systemd tmpfiles configuration
  template:
    src: tmpfiles.d_pgbouncer.conf.j2
    dest: /usr/lib/tmpfiles.d/pgbouncer.conf
    mode: 0644
  when: ansible_os_family == "Debian"

- name: Create pgbouncer configuration file
  template:
    src: pgbouncer.ini.j2
    dest: "{{ pgbouncer_conf_file }}"
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: 0600
  notify:
    - Reload pgbouncer

- name: Create pgbouncer hba file {{ pgbouncer_auth_hba_file }}
  template:
    src: pgbouncer_hba.conf.j2
    dest: "{{ pgbouncer_auth_hba_file }}"
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: 0640
  notify:
    - Reload pgbouncer

- name: Add users to userlist.txt
  copy:
    dest: "{{ pgbouncer_auth_file }}"
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: 0600
    content: |
      "stats" "passwordless"
      {% for user in pgbouncer_users %}
      "{{ user.name }}" "md5{{ (user.pass + user.name) | hash('md5') }}"
      {% endfor %}
  notify:
    - Reload pgbouncer

- name: Ensure old pgbouncer service is disabled
  service:
    name: "pgbouncer"
    enabled: false
    daemon_reload: true
    state: stopped

- name: Ensure pgbouncer service is enabled
  service:
    name: "pgbouncer@{{ item }}"
    enabled: true
  loop: "{{ pgbouncer_service_names }}"

- name: Ensure pgbouncer is running
  service:
    name: "pgbouncer@{{ item }}"
    state: started
  loop: "{{ pgbouncer_service_names }}"

- name: Configure logrotate | pgbouncer
  template:
    src: "etc_logrotate.d_pgbouncer.j2"
    dest: "/etc/logrotate.d/pgbouncer"
    mode: 0644
  when: pgbouncer_logfile is defined and pgbouncer_pidfile is defined
